#!/usr/bin/env zsh
# Install aienv and its shims into $AIENV_HOME (default $HOME/.aienv).
# Idempotent. Never edits ~/.zshrc; it only prints the line to add.
#
# The CLI is TypeScript run directly by Node (native type stripping, no build step).
# The launcher pins an absolute node path so it keeps working under a trimmed PATH;
# override with AIENV_NODE=/path/to/node.

emulate -L zsh
setopt err_exit no_unset pipe_fail

src=${0:A:h}
home=${AIENV_HOME:-$HOME/.aienv}

node=${AIENV_NODE:-$(command -v node 2>/dev/null || true)}
if [[ -z $node || ! -x $node ]]; then
  print -ru2 -- "install: node not found; install Node >= 24 or set AIENV_NODE=/path/to/node"
  exit 1
fi
# Keep the path as found (e.g. /opt/homebrew/bin/node): resolving it would pin a
# versioned Cellar path that the next upgrade deletes.
major=$("$node" -p 'process.versions.node.split(".")[0]')
if (( major < 24 )); then
  print -ru2 -- "install: $node is Node $major; aienv needs Node >= 24"
  exit 1
fi

mkdir -p -- "$home/bin" "$home/.store" "$home/lib/aienv"

# Replace the library wholesale so files deleted upstream do not linger.
rm -rf -- "$home/lib/aienv"
mkdir -p -- "$home/lib/aienv"
cp -f -- "$src"/src/*.ts "$home/lib/aienv/"
print -r -- '{"type":"module"}' > "$home/lib/aienv/package.json"

# Launcher. Home is derived from its own location so a moved install still works.
cat > "$home/bin/aienv" <<EOF
#!/bin/sh
# aienv launcher (generated by install.sh)
node='$node'
[ -x "\$node" ] || node=node
here=\$(cd "\$(dirname "\$0")/.." && pwd -P) || exit 1
exec "\$node" "\$here/lib/aienv/cli.ts" "\$@"
EOF
chmod 0755 "$home/bin/aienv"

for app in claude codex opencode; do
  cp -f -- "$src/shim" "$home/bin/$app"
  chmod 0755 "$home/bin/$app"
done

disp="$home/bin"
if [[ $home == "$HOME/.aienv" ]]; then disp='$HOME/.aienv/bin'; fi

print -r -- "installed: $home/bin/{aienv,claude,codex,opencode}"
print -r -- ""
print -r -- "Add this to your ~/.zshrc (this installer does not edit it):"
print -r -- ""
print -r -- "  export PATH=\"$disp:\$PATH\""
print -r -- ""
print -r -- "Then: exec zsh && aienv add claude"
